[project]
name = "hms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=5.0.0",
    "fastapi>=0.129.0",
    "nicegui>=3.7.1",
    "pandas>=3.0.1",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.46",
    "streamlit>=1.19.0",
    "uvicorn>=0.41.0",
    "yfinance>=0.2.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
